menu:
- {name: 'blog', url: '/blog'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/lfillbrook'}
- {icon: 'instagram', link: 'https://instagram.com/lucyfillbrook'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lucy-fillbrook'}

